def crear_diagrama_ascii():
    print("=" * 80)
    print("           FLUJO DE CONVERSACIÓN CON CONTEXTO - CLAUDE AGENT")
    print("=" * 80)
    print()

    print("┌─────────────────────────────────────────────────────────────────────────────┐")
    print("│                         CONTEXTO DE MENSAJES (Lista)                       │")
    print("│                   Mantiene el historial completo de la conversación        │")
    print("└─────────────────────────────────────────────────────────────────────────────┘")
    print("                                       ↑")
    print("                                       │")
    print("┌─────────────────────────┐           │           ┌─────────────────────────┐")
    print("│    1. PRIMER MENSAJE    │──────────┐│┌──────────│   2. CLAUDE RESPONDE    │")
    print("│       (Usuario)         │          │││          │       (API)             │")
    print("│ \"¿Qué es un coding      │          │││          │ Explica qué es un       │")
    print("│  agent?\"                │          │││          │ coding agent            │")
    print("└─────────────────────────┘          │││          └─────────────────────────┘")
    print("                                     │││")
    print("                                     ↓↓↓")
    print("┌─────────────────────────┐          │││          ┌─────────────────────────┐")
    print("│  3. RESPUESTA GUARDADA  │←─────────┘││└─────────→│  4. SEGUNDO MENSAJE     │")
    print("│    en el contexto       │           ││           │       (Usuario)         │")
    print("│                         │           ││           │ \"Escribe otra           │")
    print("│                         │           ││           │  sentencia\"             │")
    print("└─────────────────────────┘           ││           └─────────────────────────┘")
    print("                                      ││                      │")
    print("                                      ↓↓                      │")
    print("                               ┌──────────────────────────────┘")
    print("                               │")
    print("                               ↓")
    print("┌─────────────────────────────────────────────────────────────────────────────┐")
    print("│              5. CLAUDE RESPONDE CON CONTEXTO COMPLETO                       │")
    print("│          Puede referenciar la conversación anterior                         │")
    print("└─────────────────────────────────────────────────────────────────────────────┘")
    print()
    print("╔═════════════════════════════════════════════════════════════════════════════╗")
    print("║                           IMPORTANCIA DEL CONTEXTO                         ║")
    print("╠═════════════════════════════════════════════════════════════════════════════╣")
    print("║ • Sin contexto: Cada mensaje es independiente                              ║")
    print("║ • Con contexto: Claude recuerda toda la conversación                       ║")
    print("║ • Permite conversaciones más naturales y coherentes                        ║")
    print("║ • Esencial para mantener el flujo de diálogo                               ║")
    print("╚═════════════════════════════════════════════════════════════════════════════╝")
    print()

    print("FLUJO DEL CÓDIGO en 02_chat.py:")
    print("-" * 40)
    print("1. add_user_message()    → Agrega mensaje del usuario a la lista")
    print("2. chat()                → Envía TODA la lista de mensajes a Claude")
    print("3. add_assistant_message() → Agrega respuesta de Claude a la lista")
    print("4. Repetir proceso       → Cada nueva llamada incluye TODO el historial")
    print()

if __name__ == "__main__":
    crear_diagrama_ascii()